name: Bench Param

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        path: benchy

    - name: Checkout shunit2 repo
      uses: actions/checkout@v3
      with:
        repository: kward/shunit2
        path: shunit2
 
    - name: add in path
      run: echo "`pwd`/shunit2" >> $GITHUB_PATH

    - name: no param test
      run: cd ./benchy; bash ./test/defaultParamTest.sh

    - name: relative path test
      run: cd ./benchy; bash ./test/relativePathTest.sh

    - name: absolute path test
      run: cd ./benchy; bash ./test/absolutePathTest.sh

    - name: four calls error test
      run: cd ./benchy; bash ./test/fourCallsErrorTest.sh
    
    - name: four iterations error test
      run: cd ./benchy; bash ./test/fourIterationsErrorTest.sh